<?php if ($this->setting('matomo_url') && $this->setting('matomo_site_id')): ?>

<script>
var _paq = window._paq = window._paq || [];
<?php $this->trigger('matomo.js_tracking_code.before'); ?>
_paq.push(['trackPageView']);
_paq.push(['enableLinkTracking']);
(function() {
    var u=<?= json_encode($this->setting('matomo_url', '')) ?>;
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', <?= json_encode($this->setting('matomo_site_id', '')) ?>]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
})();
</script>

<?php endif; ?>
